### ISSUE TITLE
Handle measurement timestamps being in the past due to blockchain confirmation times

### ISSUE THREAD

**Issue by luzzif** [carrot-kpi/defillama-answerer#3]
Since the timestamp part of the oracle specification (i.e. the timestamp at which the measurement from DefiLlama should be taken) is offchain it could happen that in some cases an oracle creation tx gets stuck in the mempool due to low fees and the attached oracle gets created with a specification timestamp that is already in the past. This would currently result in the oracle being ignored, which is obviously not great, but even fixing that issue, this could cause some delays from when the user would want the measurement to be taken and when it is actually taken.

As an example, if a user submits a tx at t0 with a measurement timestamp of t1, but the transaction only gets confirmed on chain at t4, the measurement and the oracle answer submission will be handled at t4 instead of when the user wanted (in this case at t1). In some cases this delay could be pretty bad to say the least.

As a more robust fix we should consider moving the measurement timestamp part of the specification on-chain, validating it there too.

**Comment by guerrap** [comment]
Moving the `measurement timestamp` would mean adding it to the `_initialize` function on the oracle, and checking that it's still in the future and otherwise revert the tx?

Also if that's the case we may want to implement a logic that rejects the tx if the `measurement timestamp` is still in the future but too close, for example, the user creates an oracle at `t0` with `measurement timestamp` at `t5`, the tx gets stuck until `t4`; it's still in the past but it's too close to the desired measurement time (not quite sure if it could cause actual real issue though).

**Comment by luzzif** [comment]
Yup, agree on that. I'll add the measurement timestamp validation function and also add a mechanism so that there's a minimum time that must pass between the oracle creation and the measurement timestamp

**Comment by luzzif** [comment]
Issue addressed in https://github.com/carrot-kpi/defillama-answerer/pull/4 and https://github.com/carrot-kpi/defillama-oracle-template/pull/3
